eureka:
  instance:
    hostname: server2
  client:
    register-with-eureka: false # 指定是否向注册中心注册自己
    fetch-registry: false # 指定该机器是否能向注册中心获取信息
    service-url:
      defaultZone: http://server1:8001/eureka,http://server2:8002/eureka,http://server3:8003/eureka
server:
  port: 8002
